/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFileChooserClasses;

import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.MultiGraph;
import projecto_1.Classes.AdjMatrix;
import projecto_1.Classes.DataInterpreter;
import projecto_1.Classes.List;

/**
 *
 * @author Ignacio
 */
public class Modificar extends javax.swing.JFrame {
    private static String archivo;
    String texto;
    boolean firstRun = true;

    /**
     * Creates new form Modificar
     */
    public Modificar(String archivo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.archivo = archivo;
        
        jTextArea1.setText(archivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Iniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MODIFICAR GRAFO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 260));

        Iniciar.setText("INICIAR");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel2.setText("Para agregar usuario, ingrese el @ del usuario junto a sus relaciones.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, -1));

        jLabel3.setText("Para eliminar usuario, borre el @ del usuario junto a sus relaciones.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 510, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String modificarArchivo(String archivo) {
        boolean enSeccionUsuarios = false;
        boolean enSeccionRelaciones = false;
        boolean formatoValido = false;

        String[] lineas = archivo.split("\n");

        for (String linea : lineas) {
            if (linea.equals("usuarios")) {
                enSeccionUsuarios = true;
                enSeccionRelaciones = false;
                formatoValido = true;
                texto += linea + "\n"; 
                continue; 
            } else if (linea.equals("relaciones")) {
                enSeccionUsuarios = false;
                enSeccionRelaciones = true;
                formatoValido = true;
                texto += linea + "\n";
                continue; 
            }

            if (enSeccionUsuarios && linea.startsWith("@")) {
                texto += linea + "\n";
            } else if (enSeccionRelaciones && linea.matches("@\\w+, @\\w+")) {
                texto += linea + "\n";
            } else {
                formatoValido = false;
                break;
            }
        }

        if (!formatoValido) {
            JOptionPane.showMessageDialog(null,
                "Error: El archivo no cumple con el formato requerido.",
                "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
            return archivo;
        }

        return texto;
    }
    
    public String getData(){
        System.out.println(texto);
        return texto;
    }    
    
    private void iniciarGrafo(){ 
        String[] dataUsr = null;
        String[] dataFollow = null;
        DataInterpreter dataText = new DataInterpreter();
        List data = new List();
        if (firstRun){
            data = dataText.getDafaultData();
            dataUsr = (String[]) data.searchPos(0);
            dataFollow = (String[]) data.searchPos(1);
            firstRun = false;
        }
        else{
            String newData = this.getData();
            dataText.setData(newData);
            data = dataText.getData();
            dataUsr = (String[]) data.searchPos(0);
            dataFollow = (String[]) data.searchPos(1);
        }
        
        AdjMatrix test = new AdjMatrix(3);
        
        List stronglyConnected = new List();

        stronglyConnected = test.kosaraju(dataUsr,dataFollow);
        
        System.out.println("TERMINE???");
        
        int groupNum = stronglyConnected.isSize();
        
        for (int i = 0; i < groupNum; i++) {
            System.out.print("Grupo "+(i+1)+": ");
            int[] specGroup = (int[]) stronglyConnected.searchPos(i);
            for (int x : specGroup) {
                System.out.print(x + " ");
            }
            System.out.println();
        }
    }
    
    private Graph mostrarGrafo(String archivo) {
        Graph grafo = new MultiGraph("Grafo");
        System.setProperty("org.graphstream.ui", "swing");

        String[] lineas = archivo.split("\n");
        String seccion = "";

        for (String linea : lineas) {
            if (linea.equals("usuarios")) {
                seccion = "usuarios";
            } else if (linea.equals("relaciones")) {
                seccion = "relaciones";
            } else {
                if (seccion.equals("usuarios")) {
                    grafo.addNode(linea);
                } else if (seccion.equals("relaciones")) {
                    String[] usuarios = linea.split(", ");
                    if (usuarios.length == 2) {
                        grafo.addEdge(usuarios[0] + "_" + usuarios[1], usuarios[0], usuarios[1]);
                    }
                }
            }
        }

        return grafo;
    }
    
    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        String archivonuevo = modificarArchivo(archivo);
        System.out.println(archivonuevo);
        //iniciarGrafo();
        this.setVisible(false);
        Graph grafo = mostrarGrafo(archivonuevo);
        grafo.display();
        MostrarG ventana2 = new MostrarG(grafo, archivonuevo);
        ventana2.setVisible(true);
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar(archivo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
